---
- name: Config client VM
  hosts: tag_applicationRole_client:&tag_os_windows
  # vars:
  #   ansible_connection: winrm
  #   ansible_winrm_server_cert_validation: ignore
  vars_files:
    - vars/global.yml
  roles:
    - domain-join