---
- name: Create Active Directory on Domain Controllers
  hosts: tag_applicationRole_dc
  # vars:
  #   ansible_connection: winrm
  #   ansible_winrm_server_cert_validation: ignore
  vars_files:
    - vars/global.yml
  roles:
    - domain-create