- name: Install required packages and apt update
  apt:
    state: present
    update_cache: yes
    name: '{{ packages[ansible_distribution] }}'

- name: Create krb5.conf via template
  template:
    src: krb5.conf.j2
    dest: '/etc/krb5.conf'

- name: Update hosts file via template
  template:
    src: hosts.j2
    dest: '/etc/hosts'
    backup: yes

- name: Stop and disable built in systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Check resolv.conf is link
  stat:
    path: '/etc/resolv.conf'
  register: sym

- name: Remove symlink
  file:
    path: '/etc/resolv.conf'
    state: absent
  when: sym.stat.islink is defined and sym.stat.islink

- name: Create new resolv.conf via template
  template:
    src: resolv.conf.j2
    dest: '/etc/resolv.conf'
    backup: yes

# Join domain using realm
- name: Discover realm
  shell: 'realm discover {{ domain_name }}'
  changed_when: false

- name: Get domain list
  shell: 'realm list {{ domain_name }}'
  register: domain_list
  changed_when: false

- name: Join domain if not joined
  expect:
    command: 'realm --verbose join {{ domain_name }} -U {{ domain_admin_user }}'
    responses:
      Password for *: '{{ domain_admin_password }}'
  when: domain_list.stdout.find('domain-name') == -1

- name: Enable creating home directory automatically
  shell: 'pam-auth-update --enable mkhomedir'
  register: mkhomedir

- name: Test connection
  expect:
    command: 'ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -l {{ domain_admin_user }}@{{ domain_name }} localhost echo ok 2>&1'
    responses:
      (?i)password: '{{ domain_admin_password }}'
  register: ssh_result
  changed_when: false
