---
- name: Change SDC hostname
  win_hostname:
    name: '{{ sdc_name }}'
  when: name == 'dc-2'
  register: sdc_name_change

- name: Reboot SDC if required
  win_reboot:
    post_reboot_delay: 60
    reboot_timeout: 600
  when: sdc_name_change.reboot_required

- name: Install Features and Services
  include_tasks: 'install-feature.yml'
  with_items: '{{ pdc_required_features }}'
  loop_control:
    loop_var: feature

- name: Get current IP address of the PDC
  win_shell: |
    ((Get-NetIpAddress -InterfaceAlias 'Ethernet*') | Where-Object {$_.AddressFamily -eq '2'})[0].IPAddress
  register: sdc_ip
  changed_when: false
  ignore_errors: yes

- name: Set fact
  set_fact:
    sdc_ip: '{{ sdc_ip.stdout_lines[0] }}'
    # cacheable: yes

- name: Get Adapter name
  win_shell: |
    (Get-NetAdapter -Physical | Where-Object { $_.Name -like "Ethernet*" } | Where-Object { ($_.InterfaceDescription -like "*Hyper-V*") -or ($_.InterfaceDescription -like "*Amazon*") } | select Name)[0].Name
  register: win_dns_client_adapter_names
  changed_when: false
  ignore_errors: yes

- name: Debug
  debug:
    var: win_dns_client_adapter_names

- name: Update SDC DNS to point to PDC and itself
  win_dns_client:
    adapter_names: '{{ win_dns_client_adapter_names.stdout_lines[0] }}'
    dns_servers:
      - "{{ hostvars[groups['tag_name_dc_1'][0]]['pdc_ip'] }}"
      - "{{ hostvars[inventory_hostname]['sdc_ip'] }}"

- name: Promote SDC to 2nd domain controller
  win_domain_controller:
    dns_domain_name: '{{ domain_name }}'
    domain_admin_user: '{{ domain_admin_user }}@{{ domain_name }}'
    domain_admin_password: '{{ domain_admin_password }}'
    safe_mode_password: '{{ domain_safe_mode_password }}'
    state: domain_controller
  register: sdc_join_domain

- name: Reboot and wait until machine comes online
  block:
    - name: Reboot if required
      win_reboot:
        post_reboot_delay: 60
        reboot_timeout: 600

    - name: Wait for process to be available
      win_wait_for_process:
        process_name_exact: '{{ item }}'
        state: present
      with_items:
        - Microsoft.ActiveDirectory.WebServices
        - dns
  when: sdc_join_domain.reboot_required