---
- name: Check if required vars are defined and have value
  fail:
    msg: "Required variable {{ item }} is missing"
  when: "({{ item }} is not defined) or ({{ item }} is none) or ({{ item }} == '')"
  with_items: '{{ required_vars }}'

- name: Branching
  include_tasks: '{{ name }}.yml'